-- PUBLIC.TELEPHONES definition

-- Drop table

-- DROP TABLE PUBLIC.TELEPHONES;

-- CREATE TABLE PUBLIC.TELEPHONES (
-- 	ID BIGINT NOT NULL,
-- 	CODIGO_CIUDAD CHARACTER VARYING(255),
-- 	CODIGO_PAIS CHARACTER VARYING(255),
-- 	NUMERO CHARACTER VARYING(255),
-- 	CONSTRAINT CONSTRAINT_C PRIMARY KEY (ID)
-- );

-- PUBLIC.USERS definition

-- Drop table

-- DROP TABLE PUBLIC.USERS;

-- CREATE TABLE PUBLIC.USERS (
-- 	ID UUID DEFAULT RANDOM_UUID() NOT NULL,
-- 	ACTIVO BOOLEAN,
-- 	CLAVE CHARACTER VARYING(255) NOT NULL,
-- 	CORREO CHARACTER VARYING(255) NOT NULL,
-- 	CREADO TIMESTAMP NOT NULL,
-- 	MODIFICADO TIMESTAMP,
-- 	NOMBRE CHARACTER VARYING(255) NOT NULL,
-- 	TOKEN CHARACTER VARYING(255),
-- 	ULTIMO_LOGIN TIMESTAMP,
-- 	CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID),
-- 	CONSTRAINT UK_QS4HLSDF7L1K1U4ON057C0949 UNIQUE (CORREO)
-- );
-- CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.USERS (ID);
-- CREATE UNIQUE INDEX UK_QS4HLSDF7L1K1U4ON057C0949_INDEX_4 ON PUBLIC.USERS (CORREO);

-- PUBLIC.USERS_TELEFONOS definition

-- Drop table

-- DROP TABLE PUBLIC.USERS_TELEFONOS;

-- CREATE TABLE PUBLIC.USERS_TELEFONOS (
-- 	USER_ENTITY_ID UUID DEFAULT RANDOM_UUID() NOT NULL,
-- 	TELEFONOS_ID BIGINT NOT NULL,
-- 	CONSTRAINT UK_34T95D049X3YBWWA62GT37EPU UNIQUE (TELEFONOS_ID),
-- 	CONSTRAINT FK6PO78LUFEK3XWFCW0OFV88LKI FOREIGN KEY (TELEFONOS_ID) REFERENCES PUBLIC.TELEPHONES(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
-- 	CONSTRAINT FKMYOFP2LCQ1UAL38Q38L5463YT FOREIGN KEY (USER_ENTITY_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
-- );
-- CREATE INDEX FKMYOFP2LCQ1UAL38Q38L5463YT_INDEX_9 ON PUBLIC.USERS_TELEFONOS (USER_ENTITY_ID);
-- CREATE UNIQUE INDEX UK_34T95D049X3YBWWA62GT37EPU_INDEX_9 ON PUBLIC.USERS_TELEFONOS (TELEFONOS_ID);
-- 
-- CREATE UNIQUE INDEX PRIMARY_KEY_C ON PUBLIC.TELEPHONES (ID);



INSERT INTO PUBLIC.TELEPHONES (ID,CODIGO_CIUDAD,CODIGO_PAIS,NUMERO) VALUES
	 (1,'9','56','963009880');
INSERT INTO PUBLIC.USERS (ID,ACTIVO,CLAVE,CORREO,CREADO,MODIFICADO,NOMBRE,TOKEN,ULTIMO_LOGIN) VALUES
	 ('bc4b158f-674c-4425-a392-232172bc7f96',true,'$2a$10$j0EMEQLnh8/JTClTbi2Lr.sUrioi6.1vQntktV3H/JnLFwt3sHVBC','admin@gmail.com','2024-07-25 10:15:28.605','2024-07-25 10:51:05.291','Administrador','',NULL);
INSERT INTO PUBLIC.USERS_TELEFONOS (USER_ENTITY_ID,TELEFONOS_ID) VALUES
	 ('bc4b158f-674c-4425-a392-232172bc7f96',1);
